### ISSUE TITLE
Cant launch to new sector

### ISSUE THREAD

**Issue by Legendhyperv2** [XtarsAgency/Zeridmuth#17]
So, After i Complete the First sector, i Was ready to go to the next sector, but, it Says i required to have 1000+ Copper and 800 Lead, i Was Like, "What" Since those Resource Aren't Available in the Planet, i new it was A Bug, So, Would you mind if i Ask you to fix this Bug? Thank you

Legendhyperv2

**Comment by XtarsAgency** [comment]
Oh hey, you can solve this issue easily.
Save Core: Nouvagrad as a schematic, you then will able to travel to other sectors, this is because the mod is too simple to have custom complete campaign on it.

Sorry, i can only solve it that way of making a schematic for Core:Nouvagrad, im not that good a coding XD
